### ISSUE TITLE
How the custom controller works?

### ISSUE THREAD

**Issue by lusatiro** [willsoto/nestjs-prometheus#1141]
I would like to create a middleware with default metrics instead of annotating every endpoint.

**Comment by willsoto** [comment]
Default metrics are enabled out of the box. See the [docs](https://github.com/willsoto/nestjs-prometheus#usage). If this isn't what you mean, please elaborate or provide an example what you want to achieve.

**Comment by lusatiro** [comment]
Sry. I have "custom" metrics that I would like to create as default metrics:

If you have the time, checkout the example from Django: https://github.com/korfuri/django-prometheus/blob/master/django_prometheus/middleware.py

This metrics apply to every endpoint. I don't know it's works that way in this project.

**Comment by willsoto** [comment]
All you need to do is create a middleware as described in the [Nest.js docs](https://docs.nestjs.com/middleware). You would then inject whatever metrics you want into the middleware - similar to [this](https://github.com/willsoto/nestjs-prometheus#injecting-individual-metrics). All that would be needed at that point is to annotate your controllers with that middleware you created.

**Comment by lusatiro** [comment]
Great. That's exactly what I was thinking about. I just didn't want do some already done. Thks.
