### ISSUE TITLE
The individual metric does not show the default labels

### ISSUE THREAD

**Issue by mmaico** [willsoto/nestjs-prometheus#1346]
I created the configuration below:

`@Module({
  imports: [
    ScheduleModule.forRoot(),
    HttpModule,
    TerminusModule,
    PrometheusModule.register({
      path: '/prometheus',
      defaultMetrics: {
        config: {
          labels: {
            host: os.hostname(),
            flow: 'change-payment-method'
          }
        },
        enabled: true
      }
    }),`

And created some individual metrics
`providers: [
    makeHistogramProvider({
      name: 'http_request_duration_seconds',
      labelNames: ['method', 'queryId', 'status'],
      buckets: [100, 200, 400]
    }),`

But the individual metrics does not show the default label configured in the defaultMetrics. Is this a bug, or is it expected behavior?

**Comment by willsoto** [comment]
I think those are two separate things:

The configuration you are passing are labels for the `defaultMetrics`, which are passed to prom-client [here](https://github.com/willsoto/nestjs-prometheus/blob/main/src/module.ts#L101-L103) and then what I think you want are the new `defaultLabels` config, which are passed [here](https://github.com/willsoto/nestjs-prometheus/blob/main/src/module.ts#L105-L107). I'd assume `defaultLabels` would apply to the `defaultMetrics` but I didn't design the API so I can't be sure. Let me know if that works out for you.

**Comment by mmaico** [comment]
I think this is a bug or improvement. But my solution was to remove the "defaultMetrics" and create the default label directly in `

`
 const client = require('prom-client');

 client.register.setDefaultLabels( {
      host: os.hostname(),
      flow: 'change-payment-method'
    });
`

Solved it for me. Ideally, the "defaultMetrics" would do the same.

**Comment by willsoto** [comment]
That is what this does: https://github.com/willsoto/nestjs-prometheus#setting-default-labels

The feature is already implemented.

**Comment by mmaico** [comment]
Ahhh ok, it work to me. I was using version 4.0.0 didn't have that option yet.

thanks man!
