### ISSUE TITLE
Install dependencies Error

### ISSUE THREAD

**Issue by witcsmartian** [willsoto/nestjs-prometheus#1414]
**Repetition steps**

_step1: git clone repo;_

_step2: yarn_

**step3:  error，↓**

![image](https://user-images.githubusercontent.com/18660803/169786925-2caabeb7-2bba-4753-8bfb-65881e6f6327.png)

**Comment by willsoto** [comment]
I don't think this issue is related to this repo. Seems like you have a system issue or a node version issue.

Besides, these steps occur in CI and you can [see](https://github.com/willsoto/nestjs-prometheus/actions) it is working just fine.
