### ISSUE TITLE
Can not working when Fastify have compression

### ISSUE THREAD

**Issue by lytaitruong** [willsoto/nestjs-prometheus#1493]
## Operation system

Fastify version: 4.2.1
NestJS version: 9.0.3
Node version: 16x
Mac M1

## Description issues
    - Hi owner. Our company have idea switch from Express to Fastify because we have heard about performance of it so that we do it.
    - When integration with prometheus we tracking the Fastify get metrics is only response blank page instead like Express
    - We tracking the issues is about the compression
# Express Code
![Screen Shot 2022-07-24 at 17 47 11](https://user-images.githubusercontent.com/50540212/180643649-4598c0d3-4ef1-4afb-b227-2097ff7684b8.png)

# Fastify Code
![Screen Shot 2022-07-24 at 17 51 38](https://user-images.githubusercontent.com/50540212/180643772-087a6b07-9036-410d-a8c0-476de1e7a6a5.png)

Result: 
     - Express it have response data of metrics
     - Fastify it is not response and just blank page

Expect:
     - Fastify response data of metrics
 
Response header of metrics fastify
![Screen Shot 2022-07-24 at 17 53 16](https://user-images.githubusercontent.com/50540212/180643821-29d6ab35-3c78-463e-8443-f93159891df3.png)

**Comment by willsoto** [comment]
Right now the only way this works with Fastify is to [implement a custom controller](https://github.com/willsoto/nestjs-prometheus#providing-a-custom-controller). I am not familiar with Fastify enough to tell you what needs to go in there.

But I think this is a common enough use case that I am going to add support for it. Not sure how long it will take because I need to think on it.

**Comment by willsoto** [comment]
So I actually forgot this was implemented at some point, I have tests proving it. [I even added one with compression and it worked.](https://github.com/willsoto/nestjs-prometheus/blob/main/test/fastify.spec.ts#L46-L61) 

You will need to provide a minimal reproduction or a failing test case if you want me to dig into this issue more. Thanks
