### ISSUE TITLE
Graphql usage.

### ISSUE THREAD

**Issue by LeAlencar** [willsoto/nestjs-prometheus#1644]
Do you guys have a tutorial on using this module with graphql? I keep getting an error saying that createMetricsPlugin from apollo-metrics is not a function on my prom.module.

I was using this tutorial: https://dev.to/shinigami92/how-to-setup-prometheus-metrics-for-nestjs-graphql-67n

**Comment by willsoto** [comment]
Can you please provide a minimal reproduction of the issue?

**Comment by LeAlencar** [comment]
I'm using in a private repo. But basically I use the exact same code on this tutorial and i cannot run my application. But this is the error:

![image](https://user-images.githubusercontent.com/52898510/216200640-ae6a9999-a351-40ae-99f5-3d30e6218c66.png)

```js
import { Module } from '@nestjs/common';
import { PrometheusModule } from '@willsoto/nestjs-prometheus';
import createMetricsPlugin from 'apollo-metrics';
import { plugin as apolloTracingPlugin } from 'apollo-tracing';
import { register } from 'prom-client';

export const TRACING_PLUGIN_KEY = 'TRACING_PLUGIN_KEY';
export const METRICS_PLUGIN_KEY = 'METRICS_PLUGIN_KEY';

@Module({
  imports: [PrometheusModule.register()],
  providers: [
    {
      provide: TRACING_PLUGIN_KEY,
      useValue: apolloTracingPlugin(),
    },
    {
      provide: METRICS_PLUGIN_KEY,
      useValue: createMetricsPlugin(register),
    },
  ],
  exports: [TRACING_PLUGIN_KEY, METRICS_PLUGIN_KEY],
})
export class PromModule {}
```

**Comment by willsoto** [comment]
This stack trace has nothing to do with this module. 

My suggestion would be to check how you are importing the function in question. You are using a default import but maybe you should be using a named import or `import * as createMetricsPlugin`. I would check the docs for that module to see how they import it.
