### ISSUE TITLE
Use Gauge with collect

### ISSUE THREAD

**Issue by celianvdb** [willsoto/nestjs-prometheus#1649]
Hello,
First, thank you for this module !

I'm trying to make a gauge to monitor a cache size.
My problem is that I need to use the collect() method of the gauge and I don't understand how to do it inside a service.
I can't simply use myGauge.set() because an external module fill this cache, I don't do it in my service.

Is it possible in this library ?

Thx in advance ! 
Célian

**Comment by willsoto** [comment]
I assume you are referring to [this](https://github.com/siimon/prom-client#configuration)? The `makeGaugeProvider` 

https://github.com/willsoto/nestjs-prometheus/blob/02fbf6dbed3d66e7af71c54f5fbc8ebd13efe64d/src/metrics/gauge.ts#L8-L16

 takes all the configuration of the underlying library. If you need to to more than that - for example, customizing the injection - you should create your own gauge loosely based on how this library does it.

**Comment by celianvdb** [comment]
thx for your reply

To be more accurate, here is a simple example where I don't understand how to do :

**Comment by celianvdb** [comment]
thx for your reply

To be more accurate, here is a simple example where I don't understand how to do :

I have my Bot module where I define my gauge like in the doc :
```js
@Module({
  imports: [
    Discord.forFeature(),
    PrometheusModule.register()
  ],
  providers: [
    BotService,
    makeGaugeProvider({
      name: MetricsNames.DISCORD_CACHED_GUILDS,
      help: "Cached guilds in the discord client",
      async collect() {
        // How to call BotService.getDiscordGuildCacheSize here ?
      }
    }),
  ],
  exports: [BotService],
})
export class BotModule {}
```

And the value I want to return in my gauge is accessible from the bot service.
```js
@Injectable()
export class BotService implements OnModuleInit {
  constructor(
    @InjectDiscordClient()
    private readonly discordClient: Client,
  ) {}


  getDiscordGuildCacheSize() {
    return this.discordClient.guilds.cache.size;
  }

}
```

How could I make it to call getDiscordGuildCacheSize from collect()  ? 
I'm probably just not understanding something very stupid, sorry if it's the case :(

**Comment by willsoto** [comment]
You would need to create your own Gauge - don't use `makeGaugeProvider` - and configure the injection. Maybe something like this (**untested**)

```ts
@Module({
  providers: [
    {
      name: MetricsNames.DISCORD_CACHED_GUILDS,
       // I don't know what Discord package you are using, but you would inject
       // whatever token necessary in order to make `Client` available to the 
       // useFactory function
      inject: [],
      useFactory(discordClient: Client) {
        return new client.Gauge({
          name: MetricsNames.DISCORD_CACHED_GUILDS,
          help: "Cached guilds in the discord client",
          async collect() {
            await discordClient.whatever();
          },
        });
      },
    },
  ],
})
export class BotModule {}
```

**Comment by celianvdb** [comment]
Oh I didn't know that we can inject dependencies in provider like that ! It works, thank you very much !
