### ISSUE TITLE
how do you inject Pushgateway?

### ISSUE THREAD

**Issue by secmohammed** [willsoto/nestjs-prometheus#1651]
Hello!

I wanted to ask a quick question

if I've registered the Prometheus module at app.module.ts for example, and  I want to use Pushgateway at another module service, how can I Inject it?

**Comment by willsoto** [comment]
https://github.com/willsoto/nestjs-prometheus#pushgateway

**Comment by secmohammed** [comment]
I couldn't find that PROMETHEUS_PUSH_GATEWAY and you haven't used it as well..

**Comment by willsoto** [comment]
Docs are updated now.

**Comment by secmohammed** [comment]
Here is what happens when using 

```
    constructor(private readonly pushgateway: client.Pushgateway) {}
```



Potential solutions:
- If Pushgateway is a provider, is it part of the current LocationsModule?
- If Pushgateway is exported from a separate @Module, is that module imported within LocationsModule?

**Comment by willsoto** [comment]
Those seem like pretty typical DI issues? There are [tests](https://github.com/willsoto/nestjs-prometheus/commit/f7976360436d3c02ccafe1590ab7ddc23f633bfe) that show it's injectable. So did you confirm that the modules are imported correctly? Is `PrometheusModule` exported somewhere?

If you believe this is an issue with the library, please provide a **minimal reproduction** showing the problem.
