### ISSUE TITLE
Very long NodeJS event loop lag

### ISSUE THREAD

**Issue by shappir** [willsoto/nestjs-prometheus#1659]
We are using this project to report data to Prometheus from our NodeJS / NestJS project. We have several custom metrics - in particular histograms (created directly using `@siimon/prom-client` APIs). As a result, the overall metrics size grows up to 8MB. This results in the NodeJS event loop lag getting to be as large as 1 second!

What we see:
- Reducing the amount of data collected, e.g. by removing some metrics, improves the situation (however we would like to keep the metrics we have)
- Explicitly invoking `register.resetMetrics()` causes the lag to go down almost to 0. It then starts increasing again
- CPU usage is constant at around 15%
- CPU profile shows long time spent in Node internal network functions, such as `getPeerCertificate` and `destroySSL`

Has anyone encountered this sort of behavior? Any suggestions?

**Comment by willsoto** [comment]
Probably better to report this to https://github.com/siimon/prom-client
