### ISSUE TITLE
NestJS Monorepo app returns 404 error

### ISSUE THREAD

**Issue by veehhk** [willsoto/nestjs-prometheus#1662]
I tried to design a NestJS Monorepo application.
Prometheus applies only in the application defined in the sourceRoot section of nest-cli.json

But for the other apps in the Monorepo, /metrics route returns

`{"statusCode":404,"message":"Document was not found.","error":"Not Found"}`

**Comment by willsoto** [comment]
Without a minimal reproduction, not much I can do. 

But given your description, that seems to be working as intended. The module would only be active in the application it is registered for.
