### ISSUE TITLE
TypeScript error "Unable to resolve signature of parameter decorator when called as an expression"

### ISSUE THREAD

**Issue by ozelen** [willsoto/nestjs-prometheus#1667]
On the sample code:
```ts
import { Injectable } from '@nestjs/common';
import { Counter } from 'prom-client';
import { InjectMetric } from '@willsoto/nestjs-prometheus';

@Injectable()
export class Service {
  constructor(@InjectMetric('metric_name') public counter: Counter<string>) {}
}
```

TS compiler throws an error:
```
Unable to resolve signature of parameter decorator when called as an expression.
  Argument of type 'typeof Service' is not assignable to parameter of type 'Record<string, unknown>'.
    Index signature for type 'string' is missing in type 'typeof Service'
```

**Comment by willsoto** [comment]
What version of TypeScript?

**Comment by ozelen** [comment]
@willsoto , `4.3.5`

**Comment by willsoto** [comment]
[Works for me on TS 4.9.5](https://github.com/willsoto/nestjs-prometheus/commit/be3b25c3e2d16628d33b624df8bafd77c46ab141)

4.3.5 is a very old version of TypeScript though. You should try upgrading and, if it's still broken, creating a minimal reproduction or a failing test case.

**Comment by ozelen** [comment]
Agree. I updated TS version. Still see the error, but it's only visible in VSCode, not runtime.

**Comment by willsoto** [comment]
Perhaps VSCode isn't using whatever `tsconfig` the runtime is using?

**Comment by ozelen** [comment]
Looks like the plugin `JavaScript and TypeScript Nightly` works incorrectly. When I turned it off, the problem disappeared (along with some validation hinting though :), but VSC started performing much better).

**Comment by willsoto** [comment]
👍

**Comment by nstoya** [comment]
With typescript v5 it fails with the same error when trying to build.

**Comment by Nicklason** [comment]
> Please confirm it's not the same issue with the same resolution mentioned here: [#1667 (comment)](https://github.com/willsoto/nestjs-prometheus/issues/1667#issuecomment-1466922972)
> 
> If you believe it's actually an issue with v5, please open a new issue with a minimal reproduction of the problem.

I have the same problem. [This](https://www.typescriptlang.org/play?experimentalDecorators=true&emitDecoratorMetadata=true&target=2&ts=5.0.3#code/JYWwDg9gTgLgBAbzgSQHYCsCmBjGBDAIwBtM4BfOAMyghDgCIABVTAZxnVYHptaQJU9ANwBYAFChIsRHADCEAK6oYmKOSo069MJoC02IsEzLh4ydHhI0WXAFlMMKMGzrqtBowDuwIkVYQYCC4Wdk5dHVoHAAtMBVZTMXFGaxx8YkwACgBKcUwADyl4AzxWVjgAZVUAN2dSBHE4OF5UdigFXGgM5IxU+0dnDPoQBydsAH1UPGH6LLgwBWJnJsVlVQAuORWVKAAeVuBUAHMAPlmEMnELsSA) reproduces the problem. I have also fixed the problem and I am making a pull request for it right now.
