### ISSUE TITLE
Issues adding to grafana

### ISSUE THREAD

**Issue by ARR4NN** [willsoto/nestjs-prometheus#1722]
![image](https://github.com/willsoto/nestjs-prometheus/assets/70060472/925cac8c-7feb-40e4-b82a-32fd4af3f690)
![image](https://github.com/willsoto/nestjs-prometheus/assets/70060472/2bb54085-41ba-4410-91d8-5383f976c832)

I am having issues getting it to work

**Comment by ARR4NN** [comment]
So I add it as a prometheus instance in grafana but it errors

**Comment by Lp-Francois** [comment]
Hello 👋

This package for nestJS exports on the `/metrics` endpoint a collection of metrics.

You then need a "scraper" to retrieve these metrics from your app. It could be the grafana agent, or anything similar. Then it will likely store them in a time series database like Prometheus. (link https://grafana.com/docs/agent/latest/)

From Grafana, you can add time series database like Prometheus. By default, the agent will send metrics to the managed prometheus.
