### ISSUE TITLE
http_request_xxx

### ISSUE THREAD

**Issue by aloisiobilck** [willsoto/nestjs-prometheus#1756]
Hi
Sorry for the question, but I'm DevOps and I'm helping the development team. My doubt is why in this library I don't have the `http_request_duration_seconds_xxx` metrics? Do I need to implement it myself?

could you clarify this for me?
Thanks.

**Comment by willsoto** [comment]
This library isn't responsible for any of that. It's a wrapper for prom-client (linked in readme). Please look there.
