### ISSUE TITLE
Metrics not being computed when the application is forked into a child process

### ISSUE THREAD

**Issue by quixote15** [willsoto/nestjs-prometheus#1889]
I created a new Nestjs project, Installed the lib and then copy pasted the example in the README of a counter. That worked fine. 

However, forking the nestjs application into a sub-process and trying to increment the counter does not updates the metric value.

Even tough I increment the metric inside an infinite loop
```
let = 0; 
while (true) {
    console.log('incrementing prometheus counter in background... ' + i++);
    service.increment();
    await setTimeout(500);
  }
```

The metric endpoint returns zero

![image](https://github.com/willsoto/nestjs-prometheus/assets/12732779/10df42a7-7a7d-4672-84df-9a4ae3eaae43)

I've created repo which replicates this issue:

https://github.com/quixote15/nestjs-prometheus-fork-issue

Can anybody help me with this?

**Comment by willsoto** [comment]
Is this something that works using [`prom-client`](https://github.com/siimon/prom-client) directly?

**Comment by quixote15** [comment]
It could be something related to `prom-client` since it is a dependency of this lib but I'm just using the methods exported by `nestjs-prometheus` directly as you can see [here](https://github.com/quixote15/nestjs-prometheus-fork-issue/blob/5ccd133bea689bf3c7eb3d04538a3dadeb95e88f/src/PrometheusModule.ts#L23)


Maybe `prom-client` does not support child process ?

**Comment by willsoto** [comment]
Before I look into anything here, you will need to confirm the behavior of both `prom-client` and `NestJS` when it comes to child processes. 

Given this library is a simple thin wrapper around `prom-client`, it's unlikely the issue would be here. But before I do any work to figure it out, you will need to confirm that the underlying libraries support child processes as you'd expect and then we could say with certainty that something in this library was preventing that from working.

**Comment by quixote15** [comment]
Looking into `prom-client` repo I found that they are trying to add support to this

https://github.com/siimon/prom-client/pull/403
https://github.com/siimon/prom-client/issues/401#issue-703536115


So yeah, definetly not something in this library

**Comment by willsoto** [comment]
Great! Thanks for looking into it. If they ever get support added and it still doesn't work, please feel free to re-open this issue.
