### ISSUE TITLE
While using .registerAsync with custom controller, custom controller not working and path is ignored

### ISSUE THREAD

**Issue by murbanowicz** [willsoto/nestjs-prometheus#2279]
I found this really weird issue.
When using useFactory / registerAsync, the custom controller does not work properly.

I have to use configuration, so I moved to async creation and I hit this issue which I cannot even workaround :/

If custom controller is passed to the options while using registerAsync, the controller is not used, but the base prom controller is being used and on top of that the path is being ignored completely.

**Comment by willsoto** [comment]
Can you provide a minimal reproduction please?

**Comment by murbanowicz** [comment]
Yes please. Simple test showcasing the issue.
https://github.com/murbanowicz/nestjs-prometheus/blob/register-async-controller-issue/test/custom-controller.spec.ts

**Comment by willsoto** [comment]
Thanks. I will take a look hopefully later today or tomorrow

**Comment by murbanowicz** [comment]
Thanks! That you for such a quick reaction.

**Comment by willsoto** [comment]
Out of curiosity, do you need to actually inject anything into the controller via the `useFactory`?

**Comment by murbanowicz** [comment]
I need to inject config to set custom labels. 
I could workaround it but it is still a bug (which I can't figure out so far while looking through the code :/

**Comment by willsoto** [comment]
Just to be clear, you are trying to inject something _into the controller_ itself? 

The whole reason the "custom controller" feature was added was to support Fastify. There really isn't any logic in that controller. Setting custom labels you can do via configuration only.

**Comment by murbanowicz** [comment]
Hi,
I've tried it this way and it is still not working :(

```ts
 PrometheusModule.registerAsync({
      controller: MetricsController,
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: async (configService: ConfigService) => ({
        defaultLabels: {
          app: configService.get('SERVICE_NAME'),
          version: configService.getAppVersion(),
          ...(configService.get('ENVIRONMENT')
            ? {
                env: configService.get('ENVIRONMENT'),
              }
            : {}),
        },
      }),
    }),
    ```

**Comment by willsoto** [comment]
@murbanowicz Is tis issue resolved for you?
