### ISSUE TITLE
can't work when using the fastify server

### ISSUE THREAD

**Issue by sinchang** [willsoto/nestjs-prometheus#461]
Can we also support using the fastify server? thanks

**Comment by willsoto** [comment]
I don't use Fastify, but someone originally tried to add support for it via #260. I am happy to accept PRs. You need at least 1 test with all existing tests passing.

**Comment by willsoto** [comment]
Released as [0.1.3](https://github.com/willsoto/nestjs-prometheus/blob/master/CHANGELOG.md#013-2020-08-25). Thanks for the contribution!
