### ISSUE TITLE
Expose to a different port (ex. 9090)

### ISSUE THREAD

**Issue by ebuildy** [willsoto/nestjs-prometheus#757]
metrics should not be public, hence, this is better to expose it on a different port than the main application.

Do you have an example for this?

**Comment by willsoto** [comment]
You'd have to check the Nest.js documentation to see how to start multiple apps on different ports. You would then register this module on whatever app you want.

**Comment by simplenotezy** [comment]
Would be nice with an example of how to do this. How do you recommend setting it up @willsoto?

I found this answer: https://stackoverflow.com/a/67315107/2118665 but author does not recommend setting up multiple apps as it impacts performance negatively - not sure if this is correct though.

Alternatively, I'm curious how you protect your stats from your services. Perhaps you could also lock the route with a custom controller that checks for an API key?

**Comment by willsoto** [comment]
Here are the docs from Nest.js: https://docs.nestjs.com/faq/multiple-servers#multiple-simultaneous-servers

As to how I protect the status, I just don't expose that port or route to the internet.

**Comment by simplenotezy** [comment]
thanks @willsoto - do you happen to know if it will have a negative performance impact?

**Comment by willsoto** [comment]
I do not, sorry.

**Comment by simplenotezy** [comment]
no worries, will check myself. thanks a lot

**Comment by simplenotezy** [comment]
I am not sure how to properly configure this. If you had time, I'd highly appreciate a small example
