### ISSUE TITLE
Any example to demonstrate how to create a custom metric for every route?

### ISSUE THREAD

**Issue by gauravsharmadev** [willsoto/nestjs-prometheus#791]
I need an example that demonstrates how can I add a custom metric for every route endpoint. Say, Counter or histogram.

**Comment by willsoto** [comment]
Create the metric you want and [inject it](https://github.com/willsoto/nestjs-prometheus#injecting-individual-metrics) into the [interceptor](https://docs.nestjs.com/interceptors).
