### ISSUE TITLE
Add examples for running metric endpoint on a different port with NestJS

### ISSUE THREAD

**Issue by pragmaticivan** [willsoto/nestjs-prometheus#938]
Currently investigating that, but it's not clear yet.

**Comment by willsoto** [comment]
https://docs.nestjs.com/faq/multiple-servers#multiple-simultaneous-servers

Setup Prometheus for one and not the other.

**Comment by pragmaticivan** [comment]
Are you suggesting disabling the `/metrics` route and controller in AppModule and have 1 AppModule for each?

**Comment by willsoto** [comment]
That is how you would have to do it, yes. You would _need_ to have two different root modules (based on what I know about Nest)

**Comment by pragmaticivan** [comment]
Thoughts on adding an option to disable the default controller? Having the config set to `null` will not work with the current implementation.

**Comment by willsoto** [comment]
Why do you need to disable the default controller?

**Comment by pragmaticivan** [comment]
I still need `PrometheusModule.register` to be called on the main AppModule because I want to use the providers it's exporting. But don't want the controller to be loaded, and unfortunately, there's no way to disable that other than creating a custom empty controller (That's what I ended up doing).

The premise for that request is that `/metrics` is not exposed on the same server port as the app. It's a private entry point that is only accessed through a private network.

Here's what I ended up working on (for posterior info for newcomers).

`app-metrics.module.ts`
```ts
import { Module } from '@nestjs/common';
import { PrometheusModule } from '@willsoto/nestjs-prometheus';

@Module({
  imports: [PrometheusModule.register({
      defaultMetrics: {
        enabled: false,
      },
    })],
  controllers: [],
  providers: [],
})
export class AppMetricsModule {}
```

`app.module.ts`
```ts
@Module({
  imports: [PrometheusModule.register({
    defaultMetrics: {
      enabled: true,
    },
    controller: CustomMetricsControllerController
  })],
  controllers: [],
  providers: [],
})
export class AppModule {}
```

`app-metrics.controller.ts`

```ts
import { Controller } from "@nestjs/common";

@Controller()
export class CustomMetricsControllerController {
}
```

On `main.ts`

```ts
  const appServer = express();
  const metricsServer = express();

  const app = await NestFactory.create(AppModule, 
    new ExpressAdapter(appServer),
  );

  const metricsApp = await NestFactory.create(AppMetricsModule, 
    new ExpressAdapter(metricsServer),
  );

  await app.init();
  await metricsApp.init();

  http.createServer(appServer).listen(config.port);
  http.createServer(metricsServer).listen(config.metricsPort);
```

**Comment by willsoto** [comment]
Thanks for sharing. 

For now, disabling the default controller feels like a very bespoke use-case and your workaround isn't that bad to me. If I see more of a need for this feature, I'll reconsider.

**Comment by Papooch** [comment]
Wouldn't this solution basically instantiate two separate Nest apps with separate DI Containers (occupying twice the memory)? The providers from the `AppMetricsModule` will be different than those in `AppModule`, so how does this work? Are the underlying meters actually singletons that the injectable providers just proxy?

**Comment by soryy708** [comment]
Expanding on @Papooch's concern,
If for example we're exporting DB connection metrics (e.g. TypeORM/Prisma), looks like this workaround won't work, because `AppMetricsModule` will have its own separate db connections pool from `AppModule`, so metrics will always show idle.
