### ISSUE TITLE
Add optional HttpModule Interceptor for outbound call metrics 

### ISSUE THREAD

**Issue by pragmaticivan** [willsoto/nestjs-prometheus#953]
Context:

NestJS HttpModule uses axios and it can support interceptors.

For metrics like:
`southbound_client_errors_count`
`southbound_request_duration_seconds`

**Comment by willsoto** [comment]
I'm not totally clear on what you are asking for here but as I said [here](https://github.com/willsoto/nestjs-prometheus/issues/950#issuecomment-865338188), feel free to open a PR.
