### ISSUE TITLE
Make it possible to disable the controller

### ISSUE THREAD

**Issue by thomaschaaf** [willsoto/nestjs-prometheus#993]
I would like to not have a controller created automatically. Instead I am creating another express app in the main.ts on a different port (9090) for this purpose.

```
  const metricsServer = express();
  const metricsMiddleware = promBundle({ includeMethod: true });

  metricsServer.use(metricsMiddleware);
  metricsServer.listen(9090);
```

As long as the prom-client version is the same between the two instances I am able to use this module to easily use prometheus.

**Comment by willsoto** [comment]
See https://github.com/willsoto/nestjs-prometheus/issues/938 - it's a similar issue with a trivial workaround
